#
# deploy.yml
#
# Simple deployment of Synse Server, and the Modbus-IP plugin.
# The device config used here needs to be provided.
#
version: "3"
services:
  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    ports:
      - 5000:5000
    environment:
      SYNSE_PLUGIN_TCP: modbus-ip-plugin:5001
    links:
      - modbus-ip-plugin

  modbus-ip-plugin:
    container_name: modbus-ip-plugin
    image: vaporio/modbus-ip-plugin
    ports:
      - 5001:5001
    volumes:
      - ./devices.yml:/tmp/devices/devices.yml
      - ../../config.yml:/tmp/plugin/config.yml
    environment:
      PLUGIN_DEVICE_CONFIG: /tmp/devices
      PLUGIN_CONFIG: /tmp/plugin
