# Sample Config
version: 1.0
locations:
  - name: r1b1
    rack:
      name: rack-1
    board:
      name: board-1
devices:
  - name: power
    metadata:
      model: EG4115
      manufacturer: eGuage
    outputs:
      - type: voltage
      - type: current
      - type: power
    instances:
      - info: facility power monitoring
        location: r1b1
        data:
          id: 1
          host: 127.0.0.1
          port: 502
          slave_id: 3
          timeout: 5s
