# Sample Config
version: 1.0
locations:
  r1b1:
    rack: rack-1
    board: board-1
devices:
  - type: power
    model: EG4115
    instances:
      - id: 1
        location: r1b1
        info: Facility Power Monitoring
        host: 127.0.0.1
        port: 502
        slave_id: 3
        timeout: 5s
