# Sample Config
version: 1.0
locations:
  - name: r1b1
    rack:
      name: rack-1
    board:
      name: board-1
devices:
  - name: eg4115.power
    instances:
      - info: eGauge 4115 power meter - facility power monitoring
        location: r1b1
        handlerName: input_register
        data:
          host: 127.0.0.1
          port: 502
          slave_id: 3
          timeout: 5s
        outputs:
          - type: voltage
            info: Leg 1 to neutral RMS voltage
            data:
              address: 500
              width: 2
              type: f32
          - type: voltage
            info: Leg 2 to neutral RMS voltage
            data:
              address: 502
              width: 2
              type: f32
          - type: voltage
            info: Leg 1 to Leg 2 RMS voltage
            data:
              address: 506
              width: 2
              type: f32
